name: Sync Local Folder with S3

on:
  push:
    branches:
      - main   # or "master" if you're using that

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key-access: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-north-1'  # change to your bucket's region
      - name: Upload files to S3
        run:
          aws s3 sync ./local-folder s3://mysummerd-bucket --acl public-read

